### ISSUE TITLE
Create ERM for project

### ISSUE THREAD

**Issue by guiassemany** [IvoAlm/timeline#1]
You need to create an ERM for this project. 
This will be the first thing to do.

**Comment by guiassemany** [comment]
To accomplish this, you need to read about the topics below:

- [x] Learn how to use Workbench ERM tool.
- [x] Learn about MySQL Table engines - https://dev.mysql.com/doc/refman/5.7/en/storage-engines.html
- [x] Learn about MySQL field types - https://dev.mysql.com/doc/refman/5.7/en/data-types.html
- [x] Learn about Foreign Keys - https://dev.mysql.com/doc/refman/5.7/en/create-table-foreign-keys.html

**Comment by IvoAlm** [comment]
<img width="464" alt="project" src="https://user-images.githubusercontent.com/44970357/61127835-ce95af80-a486-11e9-9162-95d0e1e6a7da.PNG">
My diagram ER, after first review.
